# Pandas Tasks
**Name:** Areej Suleman  
**Registration:** FA23-BAI-018

In [ ]:
import numpy as np
import pandas as pd
from IPython.display import display
rng = np.random.default_rng(18)

## Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [ ]:
df = pd.DataFrame(rng.integers(1, 100, (6, 4)), columns=["A", "B", "C", "D"])
display(df)
df = df.set_index("A")
display(df)

    A   B   C   D
0  89  40  22  72
1  86  28  37   9
2  96  97  69  56
3  57  64  74  58
4  78  48  36  13
5  80  32  66  73

     B   C   D
A
89  40  22  72
86  28  37   9
96  97  69  56
57  64  74  58
78  48  36  13
80  32  66  73

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [ ]:
df = pd.DataFrame(rng.integers(1, 100, (3, 3)), columns=["A", "B", "C"], index=["X", "Y", "Z"])
display(df)
print("Y, B:", df.loc["Y", "B"])

    A   B   C
X  69  90  69
Y  88  74  94
Z  48   3  62

Y, B: 74

## Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [ ]:
df = pd.DataFrame(rng.integers(1, 10, (5, 3)), columns=["A", "B", "C"])
df["Product"] = df["A"] * df["B"]
display(df)

   A  B  C  Product
0  7  2  7       14
1  7  6  3       42
2  6  6  2       36
3  7  6  8       42
4  8  8  1       64

2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [ ]:
df = pd.DataFrame(rng.integers(1, 10, (4, 3)), columns=["A", "B", "C"])
display(df)
print("Row sums:\n", df.sum(axis=1))
print("Column sums:\n", df.sum(axis=0))

   A  B  C
0  1  9  8
1  2  3  4
2  8  5  8
3  6  5  5

Row sums:
 0    18
1     9
2    21
3    16
dtype: int64
Column sums:
 A    17
B    22
C    25
dtype: int64

## Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [ ]:
df = pd.DataFrame(rng.integers(1, 100, (5, 3)).astype(float), columns=["A", "B", "C"])
df.loc[1, "A"] = np.nan
df.loc[3, "B"] = np.nan
display(df)
display(df.fillna(df.mean()))

      A     B     C
0   6.0  39.0  88.0
1   NaN  56.0  40.0
2  68.0  87.0  93.0
3  33.0   NaN  62.0
4  78.0  85.0  74.0

       A      B     C
0   6.00  39.00  88.0
1  46.25  56.00  40.0
2  68.00  87.00  93.0
3  33.00  66.75  62.0
4  78.00  85.00  74.0

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [ ]:
df = pd.DataFrame(rng.integers(1, 100, (6, 4)).astype(float), columns=["A", "B", "C", "D"])
df.loc[0, "A"] = np.nan
df.loc[4, "C"] = np.nan
display(df)
display(df.dropna())

      A     B     C     D
0   NaN  15.0  17.0  14.0
1  73.0  47.0  13.0  85.0
2   2.0  88.0  19.0  73.0
3  40.0  37.0  70.0  18.0
4  70.0  37.0   NaN  36.0
5  23.0  12.0   6.0  87.0

      A     B     C     D
1  73.0  47.0  13.0  85.0
2   2.0  88.0  19.0  73.0
3  40.0  37.0  70.0  18.0
5  23.0  12.0   6.0  87.0

## Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [ ]:
df = pd.DataFrame({"Category": rng.choice(["A", "B", "C"], 12), "Value": rng.integers(1, 100, 12)})
display(df)
display(df.groupby("Category")["Value"].agg(["sum", "mean"]))

   Category  Value
0         A     24
1         C     81
2         A     94
3         A      7
4         C     94
5         B     26
6         B     93
7         B     65
8         B     72
9         C     47
10        B     65
11        A     10

          sum   mean
Category
A         135  33.75
B         321  64.20
C         222  74.00

2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [ ]:
df = pd.DataFrame({"Product": rng.choice(["Pen", "Book", "Bag"], 10),
                   "Category": rng.choice(["A", "B", "C"], 10),
                   "Sales": rng.integers(100, 1000, 10)})
display(df)
display(df.groupby("Category")["Sales"].sum())

  Product Category  Sales
0    Book        C    739
1     Pen        B    936
2    Book        B    239
3     Bag        B    829
4     Bag        B    327
5     Pen        B    512
6    Book        C    704
7     Bag        C    429
8     Bag        C    716
9    Book        B    875

Category
B    3718
C    2588
Name: Sales, dtype: int64

## Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [ ]:
students = pd.DataFrame({"ID": [1, 2, 3], "Name": ["Areej", "Sara", "Ali"]})
marks = pd.DataFrame({"ID": [1, 2, 3], "Marks": [90, 85, 80]})
display(pd.merge(students, marks, on="ID"))

   ID   Name  Marks
0   1  Areej     90
1   2   Sara     85
2   3    Ali     80

2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [ ]:
df1 = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df2 = pd.DataFrame({"C": [5, 6], "D": [7, 8]})
print("Along rows: missing columns produce NaN.")
display(pd.concat([df1, df2], axis=0, ignore_index=True))
print("Along columns:")
display(pd.concat([df1, df2], axis=1))

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
2  NaN  NaN  5.0  7.0
3  NaN  NaN  6.0  8.0

   A  B  C  D
0  1  3  5  7
1  2  4  6  8

Along rows: missing columns produce NaN.
Along columns:

## Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [ ]:
dates = pd.date_range("2021-01-01", "2021-12-31", freq="D")
df = pd.DataFrame({"Value": rng.integers(1, 100, len(dates))}, index=dates)
# MS labels each monthly group by its first day.
display(df.resample("MS").mean())

                Value
2021-01-01  47.258065
2021-02-01  58.500000
2021-03-01  49.645161
2021-04-01  47.266667
2021-05-01  50.516129
2021-06-01  53.233333
2021-07-01  51.129032
2021-08-01  57.741935
2021-09-01  54.933333
2021-10-01  50.193548
2021-11-01  48.666667
2021-12-01  52.483871

2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [ ]:
dates = pd.date_range("2021-01-01", "2021-12-31", freq="D")
df = pd.DataFrame({"Value": rng.integers(1, 100, len(dates))}, index=dates)
# Daily data: seven observations form a seven-day window.
df["RollingMean"] = df["Value"].rolling(window=7).mean()
display(df.head(10))  # The first six rows lack a full window.

            Value  RollingMean
2021-01-01     76          NaN
2021-01-02     34          NaN
2021-01-03     31          NaN
2021-01-04     52          NaN
2021-01-05      9          NaN
2021-01-06     23          NaN
2021-01-07      2    32.428571
2021-01-08     58    29.857143
2021-01-09     64    34.142857
2021-01-10     50    36.857143

## Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [ ]:
index = pd.MultiIndex.from_product([["A", "B"], [1, 2, 3]], names=["Group", "Item"])
df = pd.DataFrame({"Value": rng.integers(1, 100, 6)}, index=index).sort_index()
display(df)
print("Group A:")
display(df.loc["A"])
print("Single value:", df.loc[("A", 2), "Value"])
print("Items 1 to 2 in both groups:")
display(df.loc[pd.IndexSlice[:, 1:2], :])

            Value
Group Item
A     1        93
      2        32
      3        50
B     1        60
      2        24
      3        65

      Value
Item
1        93
2        32
3        50

            Value
Group Item
A     1        93
      2        32
B     1        60
      2        24

Group A:
Single value: 32
Items 1 to 2 in both groups:

2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [ ]:
index = pd.MultiIndex.from_tuples(
    [("A", "X"), ("A", "X"), ("A", "Y"), ("B", "X"), ("B", "Y"), ("B", "Y")],
    names=["Category", "SubCategory"])
df = pd.DataFrame({"Value": rng.integers(1, 100, 6)}, index=index)
display(df)
display(df.groupby(level=["Category", "SubCategory"]).sum())

                      Value
Category SubCategory
A        X                5
         X               35
         Y               72
B        X                2
         Y               63
         Y               85

                      Value
Category SubCategory
A        X               40
         Y               72
B        X                2
         Y              148

## Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [ ]:
df = pd.DataFrame({"Date": pd.to_datetime(["2021-01-01"] * 3 + ["2021-01-02"] * 3),
                   "Category": ["A", "A", "B", "A", "B", "B"],
                   "Value": rng.integers(1, 100, 6)})
display(df)
display(df.pivot_table(index="Date", columns="Category", values="Value", aggfunc="sum", fill_value=0))

        Date Category  Value
0 2021-01-01        A     13
1 2021-01-01        A     39
2 2021-01-01        B     35
3 2021-01-02        A     11
4 2021-01-02        B     78
5 2021-01-02        B     36

Category     A    B
Date
2021-01-01  52   35
2021-01-02  11  114

2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

In [ ]:
df = pd.DataFrame({"Year": np.repeat([2021, 2022], 8),
                   "Quarter": np.tile(np.repeat([1, 2, 3, 4], 2), 2),
                   "Revenue": rng.integers(1000, 5000, 16)})
display(df)
display(df.pivot_table(index="Year", columns="Quarter", values="Revenue", aggfunc="mean"))

    Year  Quarter  Revenue
0   2021        1     3314
1   2021        1     3974
2   2021        2     1674
3   2021        2     1002
4   2021        3     4456
5   2021        3     4747
6   2021        4     2984
7   2021        4     1428
8   2022        1     1004
9   2022        1     3442
10  2022        2     1882
11  2022        2     2071
12  2022        3     4537
13  2022        3     3737
14  2022        4     1356
15  2022        4     1922

Quarter       1       2       3       4
Year
2021     3644.0  1338.0  4601.5  2206.0
2022     2223.0  1976.5  4137.0  1639.0

## Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [ ]:
df = pd.DataFrame(rng.integers(1, 10, (5, 3)), columns=["A", "B", "C"])
def double(values):
    return values * 2
display(df)
display(df.apply(double))

   A  B  C
0  7  8  6
1  1  8  6
2  2  9  8
3  5  7  5
4  6  9  2

    A   B   C
0  14  16  12
1   2  16  12
2   4  18  16
3  10  14  10
4  12  18   4

2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [ ]:
df = pd.DataFrame(rng.integers(1, 10, (6, 3)), columns=["A", "B", "C"])
df["Total"] = df.apply(lambda row: row.sum(), axis=1)
display(df)

   A  B  C  Total
0  8  6  2     16
1  2  1  7     10
2  8  9  3     20
3  2  2  2      6
4  9  6  7     22
5  9  5  3     17

## Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.

In [ ]:
texts = pd.Series(rng.choice(["python", "numpy", "pandas", "learning", "coding", "data", "table"], 5, replace=False))
display(texts)
display(texts.str.upper())

0        data
1      coding
2      pandas
3       numpy
4    learning
dtype: object

0        DATA
1      CODING
2      PANDAS
3       NUMPY
4    LEARNING
dtype: object

2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [ ]:
texts = pd.Series(rng.choice(["python", "numpy", "pandas", "learning", "coding", "data", "table"], 5, replace=False))
display(texts)
display(texts.str[:3])

0     numpy
1     table
2    python
3    pandas
4      data
dtype: object

0    num
1    tab
2    pyt
3    pan
4    dat
dtype: object